name: CMake CI (Linux)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**'
      - '!**.md'
      - '!documentation/**'
      - '!.vscode/**'
      - '!*.yml'
      - '!*.yaml'
      - '.github/workflows/ci-linux.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**'
      - '!**.md'
      - '!documentation/**'
      - '!.vscode/**'
      - '!*.yml'
      - '!*.yaml'
      - '.github/workflows/ci-linux.yml'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [
            linux-clang-debug,
            linux-clang-release,
            linux-gcc-debug,
            linux-gcc-release
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Install Clang
        if: contains(matrix.preset, 'clang')
        run: |
          sudo apt-get install -y llvm clang

      - name: Configure CMake
        run: cmake --preset=${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset=${{ matrix.preset }} --target portable_package --parallel -- --verbose

      - name: Run
        working-directory: build/bin/portable
        run: |
          echo "Removing _deps for strict portable runtime test"
          rm -rf ../../_deps

          echo "Running akhenaten-tts..."
          ./akhenaten-tts --figure immigrant --lang en --phrase "Who the heck are you?" --output immigrant-hello-stranger.wav

          if [ -f immigrant-hello-stranger.wav ]; then
            echo "Output wav-file found. Test passed."
          else
            echo "Unable to find output wav-file. Test failed."
            exit 1
          fi
