name: CMake CI (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**'
      - '!**.md'
      - '!documentation/**'
      - '!.vscode/**'
      - '!*.yml'
      - '!*.yaml'
      - '.github/workflows/ci-windows.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**'
      - '!**.md'
      - '!documentation/**'
      - '!.vscode/**'
      - '!*.yml'
      - '!*.yaml'
      - '.github/workflows/ci-windows.yml'

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [
          windows-clang-cl-debug,
          windows-clang-cl-release,
          windows-msvc-debug,
          windows-msvc-release
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # windows-latest already has Ninja, clang-cl, and msvc environment

      - name: Configure CMake
        run: cmake --preset=${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset=${{ matrix.preset }} --target portable_package --parallel --verbose

      - name: Run
        shell: pwsh
        working-directory: build/bin/portable
        run: |
          Write-Host "Removing _deps for strict portable runtime test"
          if (Test-Path "..\..\_deps") {
            Remove-Item "..\..\_deps" -Recurse -Force
          }

          Write-Host "Running akhenaten-tts.exe..."
          .\akhenaten-tts.exe --figure immigrant --lang en --phrase "Who the heck are you?" --output immigrant-hello-stranger.wav

          if (Test-Path "immigrant-hello-stranger.wav") {
            Write-Host "Output wav-file found. Test passed."
          } else {
            Write-Host "Unable to find output wav-file. Test failed."
            exit 1
          }
